config/routes.rb
Rails.application.routes.draw do
  resources :workshops
  resources :service_workshops
  resources :person_workshops
  resources :locations
  resources :cities
  root "rc_workshop#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/service_workshop.rb
class ServiceWorkshop < ApplicationRecord
  belongs_to :workshop
end

app/controllers/service_workshops_controller.rb
class ServiceWorkshopsController < ApplicationController
  before_action :set_service_workshop, only: %i[ show edit update destroy ]

  # GET /service_workshops or /service_workshops.json
  def index
    @service_workshops = ServiceWorkshop.all
  end

  # GET /service_workshops/1 or /service_workshops/1.json
  def show
  end

  # GET /service_workshops/new
  def new
    @service_workshop = ServiceWorkshop.new
  end

  # GET /service_workshops/1/edit
  def edit
  end

  # POST /service_workshops or /service_workshops.json
  def create
    @service_workshop = ServiceWorkshop.new(service_workshop_params)

    respond_to do |format|
      if @service_workshop.save
        format.html { redirect_to service_workshop_url(@service_workshop), notice: "Service workshop was successfully created." }
        format.json { render :show, status: :created, location: @service_workshop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service_workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_workshops/1 or /service_workshops/1.json
  def update
    respond_to do |format|
      if @service_workshop.update(service_workshop_params)
        format.html { redirect_to service_workshop_url(@service_workshop), notice: "Service workshop was successfully updated." }
        format.json { render :show, status: :ok, location: @service_workshop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service_workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_workshops/1 or /service_workshops/1.json
  def destroy
    @service_workshop.destroy

    respond_to do |format|
      format.html { redirect_to service_workshops_url, notice: "Service workshop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_workshop
      @service_workshop = ServiceWorkshop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_workshop_params
      params.require(:service_workshop).permit(:name, :objective, :duration, :car_specialization, :workshop_id)
    end
end

app/helpers/service_workshops_helper.rb
module ServiceWorkshopsHelper
end

app/views/service_workshops/_form.html.erb
<%= form_with(model: service_workshop) do |form| %>
  <% if service_workshop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service_workshop.errors.count, "error") %> prohibited this service_workshop from being saved:</h2>

      <ul>
        <% service_workshop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :objective %>
    <%= form.text_field :objective %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.text_field :duration %>
  </div>

  <div class="field">
    <%= form.label :car_specialization %>
    <%= form.text_field :car_specialization %>
  </div>

  <div class="field">
    <%= form.label :workshop_id %>
    <%= form.text_field :workshop_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/service_workshops/edit.html.erb
<h1>Editing Service Workshop</h1>

<%= render 'form', service_workshop: @service_workshop %>

<%= link_to 'Show', @service_workshop %> |
<%= link_to 'Back', service_workshops_path %>

app/views/service_workshops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Service Workshops</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Objective</th>
      <th>Duration</th>
      <th>Car specialization</th>
      <th>Workshop</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_workshops.each do |service_workshop| %>
      <tr>
        <td><%= service_workshop.name %></td>
        <td><%= service_workshop.objective %></td>
        <td><%= service_workshop.duration %></td>
        <td><%= service_workshop.car_specialization %></td>
        <td><%= service_workshop.workshop_id %></td>
        <td><%= link_to 'Show', service_workshop %></td>
        <td><%= link_to 'Edit', edit_service_workshop_path(service_workshop) %></td>
        <td><%= link_to 'Destroy', service_workshop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service Workshop', new_service_workshop_path %>

app/views/service_workshops/new.html.erb
<h1>New Service Workshop</h1>

<%= render 'form', service_workshop: @service_workshop %>

<%= link_to 'Back', service_workshops_path %>

app/views/service_workshops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service_workshop.name %>
</p>

<p>
  <strong>Objective:</strong>
  <%= @service_workshop.objective %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @service_workshop.duration %>
</p>

<p>
  <strong>Car specialization:</strong>
  <%= @service_workshop.car_specialization %>
</p>

<p>
  <strong>Workshop:</strong>
  <%= @service_workshop.workshop_id %>
</p>

<%= link_to 'Edit', edit_service_workshop_path(@service_workshop) %> |
<%= link_to 'Back', service_workshops_path %>